name: Zenith Empire Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Proyecto
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Permisos al Gradlew
        run: chmod +x gradlew

      - name: Construir APK Imperial
        run: ./gradlew assembleRelease

      - name: Entregar el APK
        uses: actions/upload-artifact@v4
        with:
          name: Eart-Gemini-Empire-APK
          path: app/build/outputs/apk/release/*.apk
